### ISSUE TITLE
[BUG] Full directory logging isn't writing reports to each database's output directory

### ISSUE THREAD

**Issue by phoenixrising1800** [joedinsmoor/sqlite_scraper#13]
**Description:** 
dirScraper() creates a "report" directory for each parsed database, but logging doesn't currently write output to each of them.

**To Reproduce:**
1. Running sqlite_scraper.py
2. Selecting option '2' for full directory parsing
3. Note directories are created for each database in the path, but 'run.log' or 'phone_numbers.csv ... etc are not correctly written to them

**Expected Behavior(?):** 
Scraped data output files and logs such as _run.log_, _phone_numbers.csv_, and _extracted_image.png_ should be written to the correct output directory. For example, any data scraped from _226660312ssm.sqlite_ should be written to the output directory '_/sms_'

**Comment by joedinsmoor** [comment]
Fixed in commit 3a81e9a
